name: Check Strings

on:
  push:
    branches: [ master ]

jobs:
  check-strings:
    runs-on: source
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find Unused Strings
        run: ./tools/find-unused-strings.sh

      - name: Find Stale Translations
        run: ./tools/stale-translations.sh

      - name: Diff
        run: git --no-pager diff --exit-code HEAD
